-- 济企通数据库 Schema
-- Run this in Supabase SQL Editor

-- =====================================================
-- Companies table
-- =====================================================
create table if not exists public.companies (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    address text,
    business text,
    posts_count bigint default 0,
    rating decimal(2,1) default 0,
    summary text,
    has_overtime boolean default false,
    has_salary boolean default false,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Index for search
create index if not exists idx_companies_name on public.companies using gin(to_tsvector('simple', name));

-- =====================================================
-- Reviews table (approved/published reviews)
-- =====================================================
create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id) on delete cascade,
    content text not null,
    overtime text,
    salary text,
    uv bigint default 0,
    pv bigint default 0,
    is_anonymous boolean default true,
    from_id bigint,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Indexes
create index if not exists idx_reviews_company_id on public.reviews(company_id);
create index if not exists idx_reviews_created_at on public.reviews(created_at desc);

-- =====================================================
-- Review queue (pending moderation)
-- =====================================================
create table if not exists public.review_queue (
    id bigint generated by default as identity primary key,
    company_name text not null,
    content text not null,
    overtime text,
    salary text,
    from_id bigint,
    status varchar(20) default 'pending' check (status in ('pending', 'approved', 'rejected')),
    ai_confidence decimal(3,2),
    ai_flags jsonb,
    feishu_notified boolean default false,
    feishu_message_id text,
    created_at timestamptz default now(),
    processed_at timestamptz
);

-- Indexes
create index if not exists idx_review_queue_status on public.review_queue(status);
create index if not exists idx_review_queue_created_at on public.review_queue(created_at);

-- =====================================================
-- Row Level Security (RLS)
-- =====================================================

-- Enable RLS
alter table public.companies enable row level security;
alter table public.reviews enable row level security;
alter table public.review_queue enable row level security;

-- Companies: anyone can read
create policy "Anyone can view companies"
    on public.companies for select
    using (true);

-- Reviews: anyone can read, only service can insert
create policy "Anyone can view reviews"
    on public.reviews for select
    using (true);

create policy "Service can insert approved reviews"
    on public.reviews for insert
    with check (true);

-- Review queue: anyone can submit, only service can update
create policy "Anyone can submit reviews"
    on public.review_queue for insert
    with check (true);

create policy "Service can view queue"
    on public.review_queue for select
    using (true);

create policy "Service can update queue"
    on public.review_queue for update
    using (true);

-- =====================================================
-- Functions
-- =====================================================

-- Auto-update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Trigger for companies
drop trigger if exists set_updated_at on public.companies;
create trigger set_updated_at
    before update on public.companies
    for each row execute function public.handle_updated_at();

-- Trigger for reviews
drop trigger if exists set_updated_at_reviews on public.reviews;
create trigger set_updated_at_reviews
    before update on public.reviews
    for each row execute function public.handle_updated_at();

-- Function to increment posts_count when review is approved
create or replace function public.increment_posts_count()
returns trigger as $$
begin
    update public.companies
    set posts_count = posts_count + 1
    where id = new.company_id;
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_review_approved on public.reviews;
create trigger on_review_approved
    after insert on public.reviews
    for each row execute function public.increment_posts_count();
